project:
  type: book
  output-dir: "HTS-summary-notebook"
  
book:
  title: "2025 HTS Summary"
  repo-url: https://github.com/psrc/travel-studies/tree/master/2025
  search: false
  sidebar:
    logo: PSRClogo2016path.png

  chapters:
    - index.qmd # this is a required file for Quarto Book
    - Analysis/Delivery/delivery_analysis.qmd

format:
  html:
    mainfont: Poppins
    theme: [cosmo, custom.scss]  # custom formatting
    echo: false
    code-tools: true
    
execute:
  freeze: auto  # re-render only when source changes


toc: true
warnings: false
comments:  # enable commenting
  hypothesis: true