project:
  type: book
  output-dir: "HHTS-analysis-notebook"
  
book:
  title: " 2025 HHTS Summary"
  repo-url: https://github.com/psrc/soundcast/tree/base_year_2023/scripts/summarize/validation
  search: false
  sidebar:
    logo: PSRClogo2016path.png

  chapters:
    - index.qmd
    - household.qmd
    - person.qmd
    - day.qmd
    - trip.qmd
    - vehicle.qmd
    - all_location.qmd

format:
  html:
    mainfont: Poppins
    theme: 
      light: [cosmo, custom.scss]
    echo: false
    code-tools: true
    df-print: kable
    
toc: true
toc-depth: 4
# warnings: false
